CREATE DATABASE IF NOT EXISTS blog;
USE blog;

CREATE TABLE usuario
(
id_usuario INT AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
senha CHAR(60) NOT NULL,
data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
ativo TINYINT(4) NOT NULL DEFAULT'0',
adm TINYINT NOT NULL DEFAULT'0',
PRIMARY KEY(id_usuario)
);

CREATE TABLE post
(
id_post INT  NOT NULL AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
texto TEXT NOT NULL,
id_usuario INT NOT NULL,
data_criacao DATETIME NOT NULL,
data_postagem DATETIME NOT NULL,

PRIMARY KEY(id_post),
FOREIGN KEY(id_usuario) REFERENCES usuario(id_usuario)
);